# -*- coding: utf-8 -*-
"""app.py (Main Router)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3VjRaPaoGVKl5Mv_sBvhPt9C28vQsp0
"""

# -*- coding: utf-8 -*-
import streamlit as st
from streamlit_option_menu import option_menu
from utils import load_custom_css
import home
import explore
import search
import profile
import campaign
import login
import register

# --- Page Configuration ---
st.set_page_config(
    page_title="HAVEN - Crowdfunding",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Load custom CSS for consistent styling
load_custom_css()

# --- Authentication State Management ---
if "authenticated" not in st.session_state:
    st.session_state.authenticated = False

# --- Main Application Router ---
if not st.session_state.authenticated:
    # If user is not logged in, show a simple top menu for Login/Register
    selected = option_menu(
        menu_title=None,
        options=["Login", "Register"],
        icons=["box-arrow-in-right", "person-plus-fill"],
        orientation="horizontal",
    )
    if selected == "Login":
        login.show()
    elif selected == "Register":
        register.show()
else:
    # If user is logged in, show the full sidebar navigation
    with st.sidebar:
        st.title("HAVEN Menu")
        selected = option_menu(
            menu_title="Navigation",
            options=["Browse", "Explore", "Search", "Campaign", "Create Campaign", "Profile"],
            icons=["house", "compass", "search", "bullseye", "plus-circle", "person-circle"],
            menu_icon="cast",
            default_index=0
        )

        if st.button("Logout", key="logout_button"):
            st.session_state.authenticated = False
            st.rerun()

    # Route to the selected page
    if selected == "Browse":
        home.show()
    elif selected == "Explore":
        explore.show()
    elif selected == "Search":
        search.show()
    elif selected == "Campaign":
        campaign.show()
    elif selected == "Create Campaign":
        profile.show_creation_form()
    elif selected == "Profile":
        profile.show_profile_details()