# -*- coding: utf-8 -*-
"""HAVEN Crowdfunding Streamlit App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19q5nIlffbHFlcTNPvzWTB3jxvsFDineb
"""

import streamlit as st
import requests
import base64
from datetime import datetime
import json
import os
from urllib.parse import urlencode
import time
import re

# --- Page configuration ---
st.set_page_config(
    page_title="HAVEN - Crowdfunding Platform",
    page_icon="🏠",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# --- Environment variables for OAuth and Backend URL ---
# These variables are loaded from the environment, matching the keys in your crowdfunding (3).env file.
BACKEND_URL = os.getenv("BACKEND_URL", "https://haven-fastapi-backend.onrender.com")
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "your-google-client-id")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI", f"{BACKEND_URL}/auth/google/callback")
FACEBOOK_CLIENT_ID = os.getenv("FACEBOOK_CLIENT_ID", "your-facebook-app-id")
FACEBOOK_REDIRECT_URI = os.getenv("FACEBOOK_REDIRECT_URI", f"{BACKEND_URL}/auth/facebook/callback")
FRONTEND_BASE_URI = os.getenv("FRONTEND_BASE_URI", "https://haven-streamlit-frontend.onrender.com")


# --- Translation Dictionary and Term Simplification Logic ---
# Placeholder dictionary for translations
# In a real-world scenario, this would be populated by a translation service like IndicTrans2.
TRANSLATIONS = {
    'en': {
        'page_title': "HAVEN - Crowdfunding Platform",
        'tagline': "Help not just some people, but Help Humanity.",
        'home_nav': "Home",
        'trending_title': "Trending Campaigns",
        'search_title': "Search Campaigns",
        'explore_title': "Explore Categories",
        'profile_title': "User Profile",
        'login_title': "Login",
        'register_title': "Register",
        'login_prompt': "Enter Your Email",
        'password_prompt': "Enter Your Password",
        'not_registered': "Not registered?",
        'create_account': "Create an account",
        'or_signin_with': "or you can sign in with",
        'search_nav': "Search",
        'explore_nav': "Explore",
        'language': "Language",
        'select_language': "Select Language",
        'search_placeholder': "Search by keyword, category...",
        'logout': "Logout",
        'create_campaign': "Create Campaign",
        'donation_dashboard': "Donation Dashboard",
        'user_type': "User Type",
        'individual': "Individual",
        'organization': "Organization",
        'full_name': 'Full Name',
        'email_id': 'Email ID',
        'phone_number': 'Phone Number',
        'otp': 'Enter OTP',
        'password': 'Password',
        'confirm_password': 'Confirm Password',
        'address': 'Address',
        'identity_verification': 'Identity Verification (Upload any one):',
        'document_type': 'Document Type',
        'upload_document': 'Upload Document',
        'register_button': 'Register',
        'org_name': 'Organization Name',
        'org_phone': 'Organization Phone Number',
        'org_type': 'Select Organization Type',
        'org_description': 'Brief Description (max 100 chars)',
        'contact_person': 'Contact Person Name',
        'contact_email': 'Contact Email',
        'org_verification': 'Organization Verification (Required):',
        'cert_type': 'Certificate Type',
        'upload_cert': 'Upload Certificate',
        'passwords_not_match': 'Passwords do not match!',
        'day_mode': 'Day Mode',
        'night_mode': 'Night Mode'
    },
    'hi': {
        'page_title': "हेवन - क्राउडफंडिंग प्लेटफ़ॉर्म",
        'tagline': "केवल कुछ लोगों की नहीं, बल्कि मानवता की मदद करें।",
        'home_nav': "होम",
        'trending_title': "ट्रेंडिंग अभियान",
        'search_title': "अभियान खोजें",
        'explore_title': "श्रेणियाँ खोजें",
        'profile_title': "उपयोगकर्ता प्रोफ़ाइल",
        'login_title': "लॉग इन करें",
        'register_title': "पंजीकरण करें",
        'login_prompt': "अपना ईमेल दर्ज करें",
        'password_prompt': "अपना पासवर्ड दर्ज करें",
        'not_registered': "पंजीकृत नहीं हैं?",
        'create_account': "एक खाता बनाएँ",
        'or_signin_with': "या आप इसके साथ साइन इन कर सकते हैं",
        'search_nav': "खोज",
        'explore_nav': "खोज",
        'language': "भाषा",
        'select_language': "भाषा चुनें",
        'search_placeholder': "कीवर्ड, श्रेणी द्वारा खोजें...",
        'logout': "लॉग आउट",
        'create_campaign': "अभियान बनाएँ",
        'donation_dashboard': "दान डैशबोर्ड",
        'user_type': "उपयोगकर्ता प्रकार",
        'individual': "व्यक्तिगत",
        'organization': "संगठन",
        'full_name': 'पूरा नाम',
        'email_id': 'ईमेल आईडी',
        'phone_number': 'फ़ोन नंबर',
        'otp': 'ओटीपी दर्ज करें',
        'password': 'पासवर्ड',
        'confirm_password': 'पासवर्ड की पुष्टि करें',
        'address': 'पता',
        'identity_verification': 'पहचान सत्यापन (कोई भी एक अपलोड करें):',
        'document_type': 'दस्तावेज़ का प्रकार',
        'upload_document': 'दस्तावेज़ अपलोड करें',
        'register_button': 'पंजीकरण करें',
        'org_name': 'संगठन का नाम',
        'org_phone': 'संगठन का फोन नंबर',
        'org_type': 'संगठन का प्रकार चुनें',
        'org_description': 'संक्षिप्त विवरण (अधिकतम 100 वर्ण)',
        'contact_person': 'संपर्क व्यक्ति का नाम',
        'contact_email': 'संपर्क ईमेल',
        'org_verification': 'संगठन सत्यापन (आवश्यक):',
        'cert_type': 'प्रमाण पत्र का प्रकार',
        'upload_cert': 'प्रमाण पत्र अपलोड करें',
        'passwords_not_match': 'पासवर्ड मेल नहीं खाते!',
        'day_mode': 'दिन का मोड',
        'night_mode': 'रात का मोड'
    },
    'ta': {
        'page_title': "ஹெவன் - கிரவுட்ஃபண்டிங் பிளாட்ஃபார்ம்",
        'tagline': "சிலருக்கு மட்டுமல்ல, மனிதகுலத்திற்கே உதவுங்கள்.",
        'home_nav': "முகப்பு",
        'trending_title': "பிரபலமான பிரச்சாரங்கள்",
        'search_title': "பிரச்சாரங்களைத் தேடு",
        'explore_title': "பிரிவுகளை ஆராயுங்கள்",
        'profile_title': "பயனர் சுயவிவரம்",
        'login_title': "உள்நுழை",
        'register_title': "பதிவுசெய்",
        'login_prompt': "உங்கள் மின்னஞ்சலை உள்ளிடவும்",
        'password_prompt': "உங்கள் கடவுச்சொல்லை உள்ளிடவும்",
        'not_registered': "பதிவு செய்யவில்லையா?",
        'create_account': "ஒரு கணக்கை உருவாக்கவும்",
        'or_signin_with': "அல்லது நீங்கள் இவற்றுடன் உள்நுழையலாம்",
        'search_nav': "தேடல்",
        'explore_nav': "ஆராய்",
        'language': "மொழி",
        'select_language': "மொழியைத் தேர்ந்தெடுக்கவும்",
        'search_placeholder': "முக்கிய வார்த்தை, வகைப்படி தேடு...",
        'logout': "வெளியேறு",
        'create_campaign': "பிரச்சாரத்தை உருவாக்கு",
        'donation_dashboard': "நன்கொடை டாஷ்போர்டு",
        'user_type': "பயனர் வகை",
        'individual': "தனிநபர்",
        'organization': "நிறுவனம்",
        'full_name': 'முழு பெயர்',
        'email_id': 'மின்னஞ்சல் ஐடி',
        'phone_number': 'தொலைபேசி எண்',
        'otp': 'OTP ஐ உள்ளிடவும்',
        'password': 'கடவுச்சொல்',
        'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்து',
        'address': 'முகவரி',
        'identity_verification': 'அடையாளச் சரிபார்ப்பு (ஏதேனும் ஒன்றைப் பதிவேற்றவும்):',
        'document_type': 'ஆவண வகை',
        'upload_document': 'ஆவணத்தைப் பதிவேற்று',
        'register_button': 'பதிவுசெய்',
        'org_name': 'நிறுவனத்தின் பெயர்',
        'org_phone': 'நிறுவனத்தின் தொலைபேசி எண்',
        'org_type': 'நிறுவன வகையைத் தேர்ந்தெடு',
        'org_description': 'சுருக்கமான விளக்கம் (அதிகபட்சம் 100 எழுத்துக்கள்)',
        'contact_person': 'தொடர்பு நபரின் பெயர்',
        'contact_email': 'தொடர்பு மின்னஞ்சல்',
        'org_verification': 'நிறுவனச் சரிபார்ப்பு (தேவை):',
        'cert_type': 'சான்றிதழ் வகை',
        'upload_cert': 'சான்றிதழைப் பதிவேற்று',
        'passwords_not_match': 'கடவுச்சொற்கள் பொருந்தவில்லை!',
        'day_mode': 'பகல் பயன்முறை',
        'night_mode': 'இரவு பயன்முறை'
    },
    'te': {
        'page_title': "హేవెన్ - క్రౌడ్‌ఫండింగ్ ప్లాట్‌ఫారమ్",
        'tagline': "కొంతమందికి మాత్రమే కాకుండా, మానవత్వానికి సహాయం చేయండి.",
        'home_nav': "హోమ్",
        'trending_title': "ట్రెండింగ్ ప్రచారాలు",
        'search_title': "ప్రచారాలను శోధించండి",
        'explore_title': "వర్గాలను అన్వేషించండి",
        'profile_title': "వినియోగదారు ప్రొఫైల్",
        'login_title': "లాగిన్",
        'register_title': "నమోదు చేయండి",
        'login_prompt': "మీ ఇమెయిల్ నమోదు చేయండి",
        'password_prompt': "మీ పాస్‌వర్డ్‌ను నమోదు చేయండి",
        'not_registered': "నమోదు చేసుకోలేదా?",
        'create_account': "ఒక ఖాతాను సృష్టించండి",
        'or_signin_with': "లేదా మీరు దీనితో సైన్ ఇన్ చేయవచ్చు",
        'search_nav': "శోధన",
        'explore_nav': "అన్వేషణ",
        'language': "భాష",
        'select_language': "భాషను ఎంచుకోండి",
        'search_placeholder': "కీలకపదం, వర్గం ద్వారా శోధించండి...",
        'logout': "లాగ్ అవుట్",
        'create_campaign': "ప్రచారాన్ని సృష్టించండి",
        'donation_dashboard': "విరాళాల డాష్‌బోర్డ్",
        'user_type': "వినియోగదారు రకం",
        'individual': "వ్యక్తిగత",
        'organization': "సంస్థ",
        'full_name': 'పూర్తి పేరు',
        'email_id': 'ఇమెయిల్ ఐడి',
        'phone_number': 'ఫోన్ నంబర్',
        'otp': 'ఓటిపి ని నమోదు చేయండి',
        'password': 'పాస్వర్డ్',
        'confirm_password': 'పాస్వర్డ్ను నిర్ధారించండి',
        'address': 'చిరునామా',
        'identity_verification': 'గుర్తింపు ధృవీకరణ (ఏదైనా ఒకదాన్ని అప్‌లోడ్ చేయండి):',
        'document_type': 'పత్రం రకం',
        'upload_document': 'పత్రాన్ని అప్‌లోడ్ చేయండి',
        'register_button': 'నమోదు చేయండి',
        'org_name': 'సంస్థ పేరు',
        'org_phone': 'సంస్థ ఫోన్ నంబర్',
        'org_type': 'సంస్థ రకాన్ని ఎంచుకోండి',
        'org_description': 'సంక్షిప్త వివరణ (గరిష్టంగా 100 అక్షరాలు)',
        'contact_person': 'సంప్రదింపు వ్యక్తి పేరు',
        'contact_email': 'సంప్రదింపు ఇమెయిల్',
        'org_verification': 'సంస్థ ధృవీకరణ (అవసరం):',
        'cert_type': 'సర్టిఫికేట్ రకం',
        'upload_cert': 'సర్టిఫికేట్‌ను అప్‌లోడ్ చేయండి',
        'passwords_not_match': 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు!',
        'day_mode': 'పగటి మోడ్',
        'night_mode': 'రాత్రి మోడ్'
    }
}

# This dictionary simulates a backend service for term simplification.
# In a real app, this would be an API call.
SIMPLIFIED_TERMS = {
    'Crowdfunding': 'A way of raising money from a large number of people, typically via the internet.',
    'Social impact': 'The positive or negative effect of an organization, program, or policy on people and communities.',
    'Sustainability': 'The ability to exist constantly. In business, it means a company’s ability to operate without negatively impacting the environment.',
    'Philanthropy': 'The desire to promote the welfare of others, typically expressed by the generous donation of money to good causes.',
}

def get_translated_text(key, lang):
    """Retrieves translated text from the dictionary."""
    return TRANSLATIONS.get(lang, TRANSLATIONS['en']).get(key, f"Translation missing for '{key}'")


def process_content_for_simplification(text):
    """
    Scans a text for predefined complex terms and wraps them in an HTML structure
    that creates a tooltip on hover.
    """
    for term, definition in SIMPLIFIED_TERMS.items():
        # Use regex to find and replace the whole word, case-insensitive
        text = re.sub(
            r'\b' + re.escape(term) + r'\b',
            f'<span class="tooltip">{term} <span class="info-icon">i</span><span class="tooltiptext">{definition}</span></span>',
            text,
            flags=re.IGNORECASE
        )
    return text

# --- Utility functions ---
def load_logo():
    """
    Loads the HAVEN logo from the local file system and encodes it as base64.
    A fallback is provided if the file is not found in the specified path.
    """
    try:
        # Assuming the logo is available in the deployment environment
        with open("haven_logo.png", "rb") as f:
            logo_data = f.read()
        return base64.b64encode(logo_data).decode()
    except FileNotFoundError:
        # Fallback if logo file is not found
        return None

def get_profile_image():
    """Placeholder for a user's profile image."""
    return "https://placehold.co/40x40/4CAF50/FFFFFF?text=P"


def load_custom_css():
    """
    Loads custom CSS for the entire app, including theme support and new layout.
    """
    # Using Font Awesome for icons
    st.markdown('<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">', unsafe_allow_html=True)
    st.markdown(f"""
    <style>
    /* Theme variables */
    :root {{
        --day-bg-color: #e8f5e9; /* Light green as requested */
        --day-text-color: #333333;
        --day-card-bg-color: #ffffff;
        --day-nav-bg-color: #ffffff;
        --day-border-color: #e0e0e0;
        --day-secondary-text-color: #757575;

        --night-bg-color: #121212;
        --night-text-color: #e0e0e0;
        --night-card-bg-color: #1e1e1e;
        --night-nav-bg-color: #1e1e1e;
        --night-border-color: #333333;
        --night-secondary-text-color: #a0a0a0;
    }}

    /* Apply theme based on session state */
    .day-mode {{
        background-color: var(--day-bg-color);
        color: var(--day-text-color);
    }}

    .night-mode {{
        background-color: var(--night-bg-color);
        color: var(--night-text-color);
    }}

    /* New main layout using CSS Grid */
    .main-layout {{
        display: grid;
        grid-template-columns: 250px 1fr;
        grid-template-rows: 1fr;
        min-height: 100vh;
        width: 100vw;
    }}

    .sidebar {{
        grid-column: 1 / 2;
        background: var(--{st.session_state.get('theme', 'day')}-nav-bg-color);
        border-right: 1px solid var(--{st.session_state.get('theme', 'day')}-border-color);
        padding: 20px;
        display: flex;
        flex-direction: column;
        gap: 20px;
    }}
    
    .content-area {{
        grid-column: 2 / 3;
        padding: 20px;
    }}

    .top-right-bar {{
        display: flex;
        justify-content: flex-end;
        align-items: center;
        gap: 15px;
        padding-bottom: 20px;
        border-bottom: 1px solid var(--{st.session_state.get('theme', 'day')}-border-color);
        margin-bottom: 20px;
    }}

    /* --- Sidebar navigation styling --- */
    .sidebar-nav-item {{
        display: flex;
        align-items: center;
        gap: 15px;
        padding: 10px 15px;
        cursor: pointer;
        font-size: 16px;
        font-weight: 500;
        color: var(--{st.session_state.get('theme', 'day')}-secondary-text-color);
        border-radius: 8px;
        transition: background-color 0.3s ease, color 0.3s ease;
    }}

    .sidebar-nav-item:hover, .sidebar-nav-item.active {{
        background-color: #4CAF50;
        color: white;
    }}

    .sidebar-nav-item.active .nav-icon {{
        color: white;
    }}

    .sidebar-nav-item .nav-icon {{
        font-size: 20px;
        color: var(--{st.session_state.get('theme', 'day')}-secondary-text-color);
    }}

    /* --- Common styling for all pages --- */
    .main .block-container {{
        padding-top: 1rem;
        padding-bottom: 1rem;
        max-width: 100%;
        min-height: 100vh;
    }}
    
    /* User profile and donation icon styling */
    .user-profile-nav {{
        cursor: pointer;
        width: 40px;
        height: 40px;
        border-radius: 50%;
        object-fit: cover;
    }}
    
    .donation-dashboard-icon {{
        cursor: pointer;
        font-size: 24px;
        color: var(--{st.session_state.get('theme', 'day')}-text-color);
        transition: color 0.3s ease;
    }}
    
    .donation-dashboard-icon:hover {{
        color: #4CAF50;
    }}

    /* Create campaign button styling */
    .create-campaign-button {{
        width: 50px;
        height: 50px;
        background: #FF5252;
        border-radius: 50%;
        border: none;
        color: white;
        font-size: 24px;
        display: flex;
        align-items: center;
        justify-content: center;
        box-shadow: 0 4px 10px rgba(0,0,0,0.2);
        cursor: pointer;
        transition: transform 0.2s ease, box-shadow 0.2s ease;
    }}

    .create-campaign-button:hover {{
        transform: scale(1.05);
        box-shadow: 0 6px 15px rgba(0,0,0,0.3);
    }}
    
    /* Card styling */
    .login-card, .register-card, .campaign-card, .category-card {{
        background: var(--{st.session_state.get('theme', 'day')}-card-bg-color);
        border-radius: 15px;
        padding: 2rem;
        box-shadow: 0 8px 32px rgba(0,0,0,0.1);
        transition: background-color 0.3s ease, color 0.3s ease;
    }}
    
    .login-card {{ max-width: 400px; margin: 0 auto; }}
    .register-card {{ max-width: 800px; margin: 0 auto; }}
    .campaign-card {{ margin: 1rem 0; }}

    .campaign-card:hover {{ transform: translateY(-5px); }}

    .category-card {{
        text-align: center;
        box-shadow: 0 4px 16px rgba(0,0,0,0.1);
        cursor: pointer;
        transition: transform 0.3s ease;
    }}

    .category-card:hover {{ transform: translateY(-5px); }}

    .category-icon {{
        font-size: 3rem;
        margin-bottom: 1rem;
    }}

    /* Progress bar styling */
    .progress-container {{
        background: #f0f0f0;
        border-radius: 10px;
        height: 8px;
        margin: 10px 0;
    }}

    .progress-bar {{
        background: linear-gradient(90deg, #4caf50, #8bc34a);
        height: 100%;
        border-radius: 10px;
        transition: width 0.3s ease;
    }}

    /* Tooltip styles for simplification */
    .tooltip {{
        position: relative;
        display: inline-block;
    }}

    .info-icon {{
        background-color: #4CAF50;
        color: white;
        border-radius: 50%;
        width: 18px;
        height: 18px;
        font-size: 12px;
        text-align: center;
        line-height: 18px;
        font-style: normal;
        margin-left: 5px;
        cursor: pointer;
    }}

    .tooltip .tooltiptext {{
        visibility: hidden;
        width: 250px;
        background-color: #555;
        color: #fff;
        text-align: center;
        border-radius: 6px;
        padding: 10px;
        position: absolute;
        z-index: 1;
        bottom: 125%; /* Position the tooltip above the text */
        left: 50%;
        margin-left: -125px;
        opacity: 0;
        transition: opacity 0.3s;
    }}

    /* Show the tooltip when hovering over the parent span */
    .tooltip:hover .tooltiptext {{
        visibility: visible;
        opacity: 1;
    }}

    /* Typography */
    h1, h2, h3, h4, h5, h6 {{
        color: var(--{st.session_state.get('theme', 'day')}-text-color);
    }}

    p {{
        font-size: 1.1rem;
        line-height: 1.6;
        margin-bottom: 1rem;
        color: var(--{st.session_state.get('theme', 'day')}-text-color);
    }}

    a {{
        color: #4caf50;
    }}

    /* Streamlit widget overrides */
    .stTextInput > div > div > input,
    .stTextArea > div > div > textarea,
    .stFileUploader > div > div,
    .stSelectbox > div > div > div {{
        border-radius: 8px;
        border: 2px solid var(--{st.session_state.get('theme', 'day')}-border-color);
        padding: 12px;
        font-size: 16px;
        background-color: var(--{st.session_state.get('theme', 'day')}-card-bg-color);
        color: var(--{st.session_state.get('theme', 'day')}-text-color);
    }}

    .stButton > button {{
        border-radius: 8px;
        padding: 12px 24px;
        font-size: 16px;
        font-weight: 500;
        border: none;
        transition: all 0.3s ease;
        background: #4CAF50;
        color: white;
    }}

    .stButton > button:hover {{
        transform: translateY(-2px);
        background: #45a049;
    }}

    .stRadio > label {{
        color: var(--{st.session_state.get('theme', 'day')}-text-color);
    }}

    /* Hide Streamlit default elements */
    #MainMenu {{visibility: hidden;}}
    footer {{visibility: hidden;}}
    header {{visibility: hidden;}}
    .stDeployButton {{display: none;}}

    </style>
    """, unsafe_allow_html=True)


def sidebar_navigation():
    """Renders the vertical sidebar navigation for authenticated users."""
    st.markdown('<div class="sidebar">', unsafe_allow_html=True)
    
    st.markdown("<h3>HAVEN</h3>", unsafe_allow_html=True)
    
    st.markdown('<div style="display: flex; flex-direction: column; gap: 10px;">', unsafe_allow_html=True)
    
    nav_items = {
        'trending': ('fa-solid fa-fire', get_translated_text('home_nav', st.session_state.language)),
        'search': ('fa-solid fa-magnifying-glass', get_translated_text('search_nav', st.session_state.language)),
        'explore': ('fa-solid fa-compass', get_translated_text('explore_nav', st.session_state.language)),
    }
    
    for page, (icon, text) in nav_items.items():
        is_active = "active" if st.session_state.current_page == page else ""
        st.markdown(f"""
        <div class="sidebar-nav-item {is_active}" onclick="window.location.href='?page={page}'">
            <i class="nav-icon {icon}"></i>
            <span>{text}</span>
        </div>
        """, unsafe_allow_html=True)
        
    st.markdown("</div>", unsafe_allow_html=True)
    
    st.markdown("</div>", unsafe_allow_html=True)

def top_right_bar():
    """Renders the horizontal top bar with user profile and actions."""
    st.markdown('<div class="top-right-bar">', unsafe_allow_html=True)
    
    # Create Campaign button (organization only)
    if st.session_state.get('user_type') == 'organization':
        if st.button(get_translated_text('create_campaign', st.session_state.language), key="create_campaign_button"):
            st.write("Redirecting to create campaign page...")
    
    # Donation Dashboard icon
    if st.button("📝", key="donation_dashboard", help="Go to Donation Dashboard"):
        st.experimental_set_query_params(page='donations')
        st.session_state.current_page = 'donations'
        st.rerun()
    
    # User Profile image (clickable)
    profile_img_url = get_profile_image()
    profile_html = f"""
    <div style="cursor: pointer;" onclick="window.location.href = '?page=profile';">
        <img src="{profile_img_url}" class="user-profile-nav" alt="Profile">
    </div>
    """
    st.markdown(profile_html, unsafe_allow_html=True)
    
    language_and_theme_selection()
    
    # Logout button
    if st.button(get_translated_text('logout', st.session_state.language)):
        st.session_state.authenticated = False
        st.session_state.user_type = None
        st.experimental_set_query_params(page='login')
        st.rerun()
        
    st.markdown("</div>", unsafe_allow_html=True)

def language_and_theme_selection():
    """Renders the language and theme selection dropdowns."""
    lang_col, theme_col = st.columns([2, 1])
    
    with lang_col:
        languages = {
            'en': 'English',
            'hi': 'Hindi',
            'ta': 'Tamil',
            'te': 'Telugu'
        }
        
        if 'language' not in st.session_state:
            st.session_state.language = 'en'
        
        selected_language = st.selectbox(
            label=get_translated_text('select_language', st.session_state.language),
            options=list(languages.keys()),
            format_func=lambda x: languages[x],
            index=list(languages.keys()).index(st.session_state.language),
            key="language_dropdown",
            label_visibility="hidden"
        )
        if selected_language != st.session_state.language:
            st.session_state.language = selected_language
            st.experimental_set_query_params(page=st.session_state.current_page)
            st.rerun()

    with theme_col:
        if 'theme' not in st.session_state:
            st.session_state.theme = 'day'
        
        theme_options = {'day': '☀️', 'night': '🌙'}
        selected_theme = st.radio(
            "Theme",
            options=list(theme_options.keys()),
            format_func=lambda x: theme_options[x],
            index=list(theme_options.keys()).index(st.session_state.theme),
            key="theme_radio",
            horizontal=True,
            label_visibility="hidden"
        )
        if selected_theme != st.session_state.theme:
            st.session_state.theme = selected_theme
            st.rerun()

def render_logo():
    """Renders the HAVEN logo."""
    logo_data = load_logo()
    if logo_data:
        st.image(f"data:image/png;base64,{logo_data}", width=150)
    else:
        st.markdown(f"<h1>HAVEN</h1>", unsafe_allow_html=True)

# --- Page content functions ---
def login_page():
    """Renders the login page."""
    
    col1, col2, col3 = st.columns([1, 4, 1])
    with col2:
        render_logo()
        st.markdown(
            f"<h2 style='text-align: center; font-style: italic;'>{get_translated_text('tagline', st.session_state.language)}</h2>",
            unsafe_allow_html=True
        )
        
        with st.container():
            st.markdown("<div class='login-card'>", unsafe_allow_html=True)
            st.subheader(get_translated_text('login_title', st.session_state.language))
            email = st.text_input(get_translated_text('login_prompt', st.session_state.language))
            password = st.text_input(get_translated_text('password_prompt', st.session_state.language), type="password")
            
            if st.button(get_translated_text('login_title', st.session_state.language)):
                try:
                    if email and password:
                        st.success("Login successful!")
                        st.session_state.authenticated = True
                        
                        if email == "org@example.com":
                            st.session_state.user_type = "organization"
                        else:
                            st.session_state.user_type = "individual"
                        
                        st.experimental_set_query_params(page='trending')
                        st.rerun()
                    else:
                        st.error("Please enter email and password.")
                except Exception as e:
                    st.error(f"An error occurred: {e}")

            st.markdown(f"---")
            st.markdown(f"<p style='text-align: center;'>{get_translated_text('not_registered', st.session_state.language)} <a href='?page=register' style='color: #42a5f5;'>{get_translated_text('create_account', st.session_state.language)}</a></p>", unsafe_allow_html=True)
            st.markdown(f"<p style='text-align: center;'>{get_translated_text('or_signin_with', st.session_state.language)}</p>", unsafe_allow_html=True)
            
            col1, col2 = st.columns(2)
            with col1:
                oauth_login_button("google", "Google", "<i class='fa-brands fa-google'></i>")
            with col2:
                oauth_login_button("facebook", "Facebook", "<i class='fa-brands fa-facebook'></i>")
            
            st.markdown("</div>", unsafe_allow_html=True)

def oauth_login_button(provider, text, icon):
    """Create OAuth login button with popup functionality"""
    button_class = f"{provider}-btn oauth-button"
    oauth_url = "#"
    button_html = f"""
    <button class="{button_class}">
        {icon} {text}
    </button>
    """
    st.markdown(button_html, unsafe_allow_html=True)


def register_page():
    """Renders the registration page with forms for individuals and organizations."""
    lang = st.session_state.get('language', 'en')
    
    col1, col2, col3 = st.columns([1, 4, 1])
    with col2:
        render_logo()
        st.markdown('<div class="register-card">', unsafe_allow_html=True)

        st.markdown(f"## {get_translated_text('register_title', lang)}")

        account_type = st.selectbox("Select Account Type", [get_translated_text('individual', lang), get_translated_text('organization', lang)])

        if account_type == get_translated_text('individual', lang):
            st.markdown(f"### {get_translated_text('register_title', lang)} {get_translated_text('individual', lang)}")
            with st.form("individual_register"):
                col_i1, col_i2 = st.columns(2)
                with col_i1:
                    full_name = st.text_input(get_translated_text('full_name', lang), placeholder="R PRAKASH")
                    email = st.text_input(get_translated_text('email_id', lang), placeholder="prakashr00@rediffmail.com")
                    phone = st.text_input(get_translated_text('phone_number', lang), placeholder="09936528585")
                    otp = st.text_input(get_translated_text('otp', lang), placeholder=get_translated_text('otp', lang))

                with col_i2:
                    password = st.text_input(get_translated_text('password', lang), type="password")
                    confirm_password = st.text_input(get_translated_text('confirm_password', lang), type="password")
                    address = st.text_area(get_translated_text('address', lang), placeholder=get_translated_text('address', lang))

                    st.markdown(f"**{get_translated_text('identity_verification', lang)}**")
                    document_type = st.selectbox(get_translated_text('document_type', lang), ["Aadhar Card", "PAN Card", "Passport", "Driving License", "Voter ID"])
                    document_file = st.file_uploader(get_translated_text('upload_document', lang), type=['pdf', 'jpg', 'png'])

                register_btn = st.form_submit_button(get_translated_text('register_button', lang), use_container_width=True)

                if register_btn:
                    if password == confirm_password:
                        st.success(f"{get_translated_text('individual', lang)} {get_translated_text('register_button', lang).lower()} successful! You can now log in.")
                        st.session_state.current_page = "login"
                        st.rerun()
                    else:
                        st.error(get_translated_text('passwords_not_match', lang))

        else: # Organization
            st.markdown(f"### {get_translated_text('register_title', lang)} {get_translated_text('organization', lang)}")
            with st.form("organization_register"):
                col_o1, col_o2 = st.columns(2)
                with col_o1:
                    org_name = st.text_input(get_translated_text('org_name', lang), placeholder=get_translated_text('org_name', lang))
                    org_phone = st.text_input(get_translated_text('org_phone', lang), placeholder=get_translated_text('org_phone', lang))
                    org_type = st.selectbox(get_translated_text('org_type', lang), ["NGO", "Non-Profit", "Social Enterprise", "Charity", "Foundation"])
                    org_description = st.text_area(get_translated_text('org_description', lang), placeholder=get_translated_text('org_description', lang), max_chars=100)

                with col_o2:
                    contact_person = st.text_input(get_translated_text('contact_person', lang))
                    contact_email = st.text_input(get_translated_text('contact_email', lang))
                    password = st.text_input(get_translated_text('password', lang), type="password")
                    confirm_password = st.text_input(get_translated_text('confirm_password', lang), type="password")

                    st.markdown(f"**{get_translated_text('org_verification', lang)}**")
                    cert_type = st.selectbox(get_translated_text('cert_type', lang), ["Certificate of Incorporation", "GST Certificate", "12A Certificate", "80G Certificate", "FCRA Certificate"])
                    cert_file = st.file_uploader(get_translated_text('upload_cert', lang), type=['pdf', 'jpg', 'png'])

                register_btn = st.form_submit_button(get_translated_text('register_button', lang), use_container_width=True)

                if register_btn:
                    if password == confirm_password:
                        st.success(f"{get_translated_text('organization', lang)} {get_translated_text('register_button', lang).lower()} successful! You can now log in.")
                        st.session_state.current_page = "login"
                        st.rerun()
                    else:
                        st.error(get_translated_text('passwords_not_match', lang))

        st.markdown(f"""
        <div style="text-align: center; margin: 20px 0;">
            {get_translated_text('not_registered', lang)} <a href="?page=login" style="color: #4caf50; text-decoration: none;">{get_translated_text('login_title', lang)}</a>
        </div>
        """, unsafe_allow_html=True)

        st.markdown('</div>', unsafe_allow_html=True)


def trending_page():
    """Renders the trending campaigns page with term simplification."""
    
    st.title(get_translated_text('trending_title', st.session_state.language))

    sample_text = """
    We are launching a new initiative to promote Sustainability and a positive Social impact in local communities. 
    Our mission is to use Crowdfunding to support various Philanthropy projects.
    """
    
    processed_text = process_content_for_simplification(sample_text)
    
    st.markdown(f"<h3>About this Initiative</h3>", unsafe_allow_html=True)
    st.markdown(f"<p>{processed_text}</p>", unsafe_allow_html=True)

    st.write("Displaying the top trending campaigns.")


def search_page():
    """Renders the search campaigns page."""
    
    st.title(get_translated_text('search_title', st.session_state.language))
    st.write("Search for campaigns.")


def explore_page():
    """Renders the explore categories page."""
    
    st.title(get_translated_text('explore_title', st.session_state.language))
    st.write("Explore campaigns by category.")


def profile_page():
    """Renders the user profile page."""
    
    st.title(get_translated_text('profile_title', st.session_state.language))
    st.write("Display user profile details.")


def campaign_detail_page(campaign_id):
    """Renders a single campaign detail page."""
    
    st.title(f"Campaign Details: {campaign_id}")
    st.write("Display details for a specific campaign.")

def donation_dashboard_page():
    """Renders a placeholder for the donation dashboard."""
    
    st.title(get_translated_text('donation_dashboard', st.session_state.language))
    st.write("This page will show a dashboard of your donations.")

# Main application
def main():
    # Initialize session state variables if they don't exist
    if 'authenticated' not in st.session_state:
        st.session_state.authenticated = False
    if 'language' not in st.session_state:
        st.session_state.language = 'en'
    if 'current_page' not in st.session_state:
        st.session_state.current_page = 'login'
    if 'user_type' not in st.session_state:
        st.session_state.user_type = None
    if 'theme' not in st.session_state:
        st.session_state.theme = 'day'

    # Get page from URL parameters
    query_params = st.experimental_get_query_params()
    page = query_params.get('page', ['login'])[0]
    st.session_state.current_page = page
    
    # Load custom CSS and set body class
    load_custom_css()
    st.markdown(f'<body class="{st.session_state.theme}-mode">', unsafe_allow_html=True)

    # Logic for authenticated vs unauthenticated layout
    if st.session_state.authenticated:
        # Authenticated users get the new sidebar layout
        st.markdown('<div class="main-layout">', unsafe_allow_html=True)
        sidebar_navigation()
        st.markdown('<div class="content-area">', unsafe_allow_html=True)
        top_right_bar()
        
        # Page routing
        if page == 'login' or page == 'register':
            st.experimental_set_query_params(page='trending')
            trending_page()
        elif page == 'trending':
            trending_page()
        elif page == 'search':
            search_page()
        elif page == 'explore':
            explore_page()
        elif page == 'profile':
            profile_page()
        elif page.startswith('campaign_'):
            campaign_id = page.split('_')[1]
            campaign_detail_page(campaign_id)
        elif page == 'donations':
            donation_dashboard_page()

        st.markdown('</div></div>', unsafe_allow_html=True)
    else:
        # Unauthenticated users get a simplified, centered layout
        if page not in ['login', 'register']:
            st.experimental_set_query_params(page='login')
            page = 'login'
            st.session_state.current_page = 'login'
        
        # Render login/register pages
        if page == 'login':
            login_page()
        elif page == 'register':
            register_page()
            
    st.markdown('</body>', unsafe_allow_html=True)

if __name__ == "__main__":
    main()
