# -*- coding: utf-8 -*-
"""home.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_v4EUPU0cIL6DCzmc8aTuhOCby33PTv
"""

import streamlit as st
from utils import get_all_campaigns, render_logo
from streamlit_card import card
from streamlit_extras.badges import badge

def show():
    render_logo()
    st.header("Browse Campaigns")

    all_campaigns = get_all_campaigns()
    if not all_campaigns:
        st.info("No campaigns found.")
        return

    # Create a responsive 3-column grid for the campaigns
    cols = st.columns(3)
    for i, campaign in enumerate(all_campaigns):
        with cols[i % 3]:
            # Display a verification status badge based on the workflow
            if campaign['verified']:
                badge(type="success", label="Verified")
            else:
                badge(type="warning", label="Under Review")

            # Display the campaign information using a card
            card(
                title=campaign['title'],
                text=f"Raised: ${campaign['current_amount']:,} of ${campaign['target_amount']:,}",
                image=campaign['image'],
                url="#" # In a real app, this would link to the specific campaign page
            )