# -*- coding: utf-8 -*-
"""login.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pODJ37tUEEq6tQBy96GqcnBja7fFtpMd
"""

import streamlit as st
import requests
from utils import render_logo, BACKEND_URL
from streamlit_notify import notify

def show():
    render_logo()
    with st.container(border=True):
        st.markdown("<h3 style='text-align: center;'>Login to HAVEN</h3>", unsafe_allow_html=True)
        with st.form(key='login_form'):
            email = st.text_input("Email", help="Use 'individual@test.com' or 'org@test.com'")
            password = st.text_input("Password", type="password", help="Use 'password123'")

            if st.form_submit_button("Login"):
                if email and password:
                    try:
                        response = requests.post(
                            f"{BACKEND_URL}/api/login",
                            json={"email": email, "password": password}
                        )
                        response.raise_for_status() # Raises an exception for bad responses (4xx or 5xx)

                        data = response.json()
                        st.session_state.authenticated = True
                        st.session_state.token = data['token']
                        st.session_state.user_type = data['user_type'] # Store the user type
                        st.rerun()

                    except requests.exceptions.HTTPError as err:
                        if err.response.status_code == 401:
                            notify("Incorrect email or password.", "error")
                        else:
                            notify(f"An error occurred: {err}", "error")
                    except requests.exceptions.RequestException as err:
                        notify(f"Could not connect to the backend: {err}", "error")
                else:
                    notify("Please enter both email and password.", "error")