# -*- coding: utf-8 -*-
"""register.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YtPAyxZ7UmCcV6PSSqxD27O3WdbQduY
"""

import streamlit as st
from utils import get_translated_text, render_logo
from streamlit_extras.pdf_viewer import pdf_viewer
from streamlit_notify import notify

def show():
    if 'language' not in st.session_state:
        st.session_state.language = 'en'
    lang = st.session_state.get('language', 'en')

    lang_map_display = {'English': 'en', 'हिन्दी': 'hi', 'தமிழ்': 'ta', 'తెలుగు': 'te'}
    lang_map_keys = list(lang_map_display.keys())
    selected_lang_display = st.selectbox(
        "Select Language", lang_map_keys,
        index=lang_map_keys.index(next(k for k, v in lang_map_display.items() if v == lang))
    )
    st.session_state.language = lang_map_display[selected_lang_display]
    lang = st.session_state.language

    col1, col2, col3 = st.columns([1, 4, 1])
    with col2:
        render_logo()
        with st.container(border=True):
            st.markdown(f"## {get_translated_text('register_title', lang)}")
            account_type = st.selectbox("Account Type", [get_translated_text('individual', lang), get_translated_text('organization', lang)])

            if account_type == get_translated_text('individual', lang):
                with st.form("individual_register"):
                    full_name = st.text_input(get_translated_text('full_name', lang))
                    email = st.text_input(get_translated_text('email_id', lang))
                    password = st.text_input(get_translated_text('password', lang), type="password")
                    confirm_password = st.text_input(get_translated_text('confirm_password', lang), type="password")
                    document_file = st.file_uploader(get_translated_text('upload_document', lang), type=['pdf', 'jpg', 'png'])

                    if st.form_submit_button(get_translated_text('register_button', lang)):
                        if password == confirm_password:
                            notify("Registration successful! Please log in.", "success")
                        else:
                            notify(get_translated_text('passwords_not_match', lang), "error")
            else:
                with st.form("organization_register"):
                    org_name = st.text_input(get_translated_text('org_name', lang))
                    contact_email = st.text_input(get_translated_text('contact_email', lang))
                    password = st.text_input(get_translated_text('password', lang), type="password")
                    confirm_password = st.text_input(get_translated_text('confirm_password', lang), type="password")
                    cert_file = st.file_uploader(get_translated_text('upload_cert', lang), type=['pdf', 'jpg', 'png'])

                    if st.form_submit_button(get_translated_text('register_button', lang)):
                        if password == confirm_password:
                            notify("Registration successful! Please log in.", "success")
                        else:
                            notify(get_translated_text('passwords_not_match', lang), "error")