# HAVEN Crowdfunding Platform - Secrets Template
# Copy this file to secrets.toml and fill in your actual values
# This template is safe to commit to GitHub

# Backend API Configuration
BACKEND_URL = "https://haven-fastapi-backend.onrender.com"

# OAuth Configuration
[oauth]
google_client_id = "your-google-client-id-here"
google_client_secret = "your-google-client-secret-here"
facebook_app_id = "your-facebook-app-id-here"
facebook_app_secret = "your-facebook-app-secret-here"

# Session Configuration
[session]
secret_key = "your-session-secret-key-here"
max_age = 3600

# Translation Service Configuration
[translation]
enabled = true
default_language = "en"
cache_ttl = 3600

# Simplification Service Configuration
[simplification]
enabled = true
default_level = "simple"
cache_ttl = 7200

# Feature Flags
[features]
translation_enabled = true
simplification_enabled = true
oauth_enabled = true
analytics_enabled = true
fraud_detection_enabled = true

# Performance Settings
[performance]
cache_ttl = 3600
max_requests_per_minute = 60
batch_size = 8

# Development Configuration
[development]
debug_mode = false
auto_reload = true
show_error_details = false

# Production Configuration
[production]
ssl_required = true
secure_cookies = true
log_level = "INFO"